package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotifyGroup generated by hbm2java
 */
@Entity
@Table(name = "psd_notify_group")
public class NotifyGroup implements java.io.Serializable {

	private static final long serialVersionUID = 1705015160887074044L;
	
	private Integer notifyGroupId;
	private String name;
	private Date createSysdate;
	private Date updateSysdate;
	private Set<NotifyGroupEmail> notifyGroupEmails;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "notify_group_id", unique = true, nullable = false)
	public Integer getNotifyGroupId() {
		return this.notifyGroupId;
	}

	public void setNotifyGroupId(Integer notifyGroupId) {
		this.notifyGroupId = notifyGroupId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "notifyGroup")
	public Set<NotifyGroupEmail> getNotifyGroupEmails() {
		return notifyGroupEmails;
	}

	public void setNotifyGroupEmails(Set<NotifyGroupEmail> notifyGroupEmails) {
		this.notifyGroupEmails = notifyGroupEmails;
	}

}
