package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

import com.untd.database.poseidon.model.Severity;

/**
 * NotifyGroupEmail generated by hbm2java
 */
@Entity
@Table(name = "psd_notify_group_email")
public class NotifyGroupEmail implements java.io.Serializable {

	private static final long serialVersionUID = 1944469361756182341L;
	
	private Integer notifyGroupEmailId;
	private NotifyGroup notifyGroup;
	private Severity severity;
	private String emailAddress;
	private Date createSysdate;
	private Date updateSysdate;


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "notify_group_email_id", unique = true, nullable = false)
	public Integer getNotifyGroupEmailId() {
		return this.notifyGroupEmailId;
	}

	public void setNotifyGroupEmailId(Integer notifyGroupEmailId) {
		this.notifyGroupEmailId = notifyGroupEmailId;
	}

	@Column(name = "severity", nullable = false)
	@Type(type = "com.untd.database.poseidon.model.database.types.SeverityUserType")
	public Severity getSeverity() {
		return this.severity;
	}

	public void setSeverity(Severity severity) {
		this.severity = severity;
	}

	@Column(name = "email_address", nullable = false, length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "notify_group_id", nullable = false)
	public NotifyGroup getNotifyGroup() {
		return notifyGroup;
	}

	public void setNotifyGroup(NotifyGroup notifyGroup) {
		this.notifyGroup = notifyGroup;
	}

}
