package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScriptTargetColLog generated by hbm2java
 */
@Entity
@Table(name = "psd_script_target_col_log")
public class ScriptTargetColLog implements java.io.Serializable {

	private static final long serialVersionUID = -6155377187700336067L;
	
	private Integer scriptTargetColLogId;
	private ScriptTargetRowLog scriptTargetRowLog;
	private int columnNumber;
	private String columnValue;
	private Date createSysdate;
	private Date updateSysdate;	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "script_target_col_log_id", unique = true, nullable = false)
	public Integer getScriptTargetColLogId() {
		return this.scriptTargetColLogId;
	}

	public void setScriptTargetColLogId(Integer scriptTargetColLogId) {
		this.scriptTargetColLogId = scriptTargetColLogId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "script_target_row_log_id", nullable = false)
	public ScriptTargetRowLog getScriptTargetRowLog() {
		return scriptTargetRowLog;
	}

	public void setScriptTargetRowLog(ScriptTargetRowLog scriptTargetRowLog) {
		this.scriptTargetRowLog = scriptTargetRowLog;
	}

	@Column(name = "column_number", nullable = false)
	public int getColumnNumber() {
		return this.columnNumber;
	}

	public void setColumnNumber(int columnNumber) {
		this.columnNumber = columnNumber;
	}

	@Column(name = "column_value", nullable = false, length = 65535)
	public String getColumnValue() {
		return this.columnValue;
	}

	public void setColumnValue(String columnValue) {
		this.columnValue = columnValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

}
