package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScriptLog generated by hbm2java
 */
@Entity
@Table(name = "psd_script_log")
public class ScriptLog implements java.io.Serializable {

	private static final long serialVersionUID = -3855505201401816674L;
	
	private Integer scriptLogId;
	private int scriptId;
	private int serverId;
	private Date startDate;
	private Date finishDate;
	private int statusNumber;
	private int errorStatusCode;
	private int triggerStatusCode;
	private Date createSysdate;
	private Date updateSysdate;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "script_log_id", unique = true, nullable = false)
	public Integer getScriptLogId() {
		return this.scriptLogId;
	}

	public void setScriptLogId(Integer scriptLogId) {
		this.scriptLogId = scriptLogId;
	}

	@Column(name = "script_id", nullable = false)
	public int getScriptId() {
		return this.scriptId;
	}

	public void setScriptId(int scriptId) {
		this.scriptId = scriptId;
	}

	@Column(name = "server_id", nullable = false)
	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finish_date", length = 19)
	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	@Column(name = "status_number", nullable = false)
	public int getStatusNumber() {
		return this.statusNumber;
	}

	public void setStatusNumber(int statusNumber) {
		this.statusNumber = statusNumber;
	}

	@Column(name = "error_status_code", nullable = false)
	public int getErrorStatusCode() {
		return this.errorStatusCode;
	}

	public void setErrorStatusCode(int errorStatusCode) {
		this.errorStatusCode = errorStatusCode;
	}

	@Column(name = "trigger_status_code", nullable = false)
	public int getTriggerStatusCode() {
		return this.triggerStatusCode;
	}

	public void setTriggerStatusCode(int triggerStatusCode) {
		this.triggerStatusCode = triggerStatusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

}
