package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ScriptGroup generated by hbm2java
 */
@Entity
@Table(name = "psd_script_group", uniqueConstraints = @UniqueConstraint(columnNames = {
		"target_group_id", "script_id" }) )
public class ScriptGroup implements java.io.Serializable {

	private static final long serialVersionUID = 5511944292083096507L;
	
	private Integer scriptGroupId;
	private int targetGroupId;
	private int scriptId;
	private Date createSysdate;
	private Date updateSysdate;

	public ScriptGroup() {
	}

	public ScriptGroup(int targetGroupId, int scriptId, Date createSysdate, Date updateSysdate) {
		this.targetGroupId = targetGroupId;
		this.scriptId = scriptId;
		this.createSysdate = createSysdate;
		this.updateSysdate = updateSysdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "script_group_id", unique = true, nullable = false)
	public Integer getScriptGroupId() {
		return this.scriptGroupId;
	}

	public void setScriptGroupId(Integer scriptGroupId) {
		this.scriptGroupId = scriptGroupId;
	}

	@Column(name = "target_group_id", nullable = false)
	public int getTargetGroupId() {
		return this.targetGroupId;
	}

	public void setTargetGroupId(int targetGroupId) {
		this.targetGroupId = targetGroupId;
	}

	@Column(name = "script_id", nullable = false)
	public int getScriptId() {
		return this.scriptId;
	}

	public void setScriptId(int scriptId) {
		this.scriptId = scriptId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

}
