package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScriptPersonNotification generated by hbm2java
 */
@Entity
@Table(name = "psd_script_person_notification")
public class ScriptPersonNotification implements java.io.Serializable {

	private static final long serialVersionUID = -2656674391735260166L;
	
	private Integer scriptPersonNotificationId;
	private Script script;
	private String emailAddress;
	private Date createSysdate;
	private Date updateSysdate;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "script_person_notification_id", unique = true, nullable = false)
	public Integer getScriptPersonNotificationId() {
		return this.scriptPersonNotificationId;
	}

	public void setScriptPersonNotificationId(Integer scriptPersonNotificationId) {
		this.scriptPersonNotificationId = scriptPersonNotificationId;
	}

	@Column(name = "email_address", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "script_id", nullable = false)
	public Script getScript() {
		return script;
	}

	public void setScript(Script script) {
		this.script = script;
	}

}
