package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * ScriptTargetLog generated by hbm2java
 */
@Entity
@Table(name = "psd_script_target_log")
public class ScriptTargetLog implements java.io.Serializable {

	private static final long serialVersionUID = -6254936206346328354L;
	
	private Integer scriptTargetLogId;
	private int scriptLogId;
	private int targetId;
	private Date startDate;
	private Date finishDate;
	private int statusNumber;
	private String errorMessage;
	private Integer severity;
	private Date createSysdate;
	private Date updateSysdate;
	private Set<ScriptTargetRowLog> scriptTargetRowLogs = new HashSet<ScriptTargetRowLog>();

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "script_target_log_id", unique = true, nullable = false)
	public Integer getScriptTargetLogId() {
		return this.scriptTargetLogId;
	}

	public void setScriptTargetLogId(Integer scriptTargetLogId) {
		this.scriptTargetLogId = scriptTargetLogId;
	}

	@Column(name = "script_log_id", nullable = false)
	public int getScriptLogId() {
		return this.scriptLogId;
	}

	public void setScriptLogId(int scriptLogId) {
		this.scriptLogId = scriptLogId;
	}

	@Column(name = "target_id", nullable = false)
	public int getTargetId() {
		return this.targetId;
	}

	public void setTargetId(int targetId) {
		this.targetId = targetId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finish_date", length = 19)
	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	@Column(name = "status_number", nullable = false)
	public int getStatusNumber() {
		return this.statusNumber;
	}

	public void setStatusNumber(int statusNumber) {
		this.statusNumber = statusNumber;
	}

	@Column(name = "error_message", length = 65535)
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "severity")
	public Integer getSeverity() {
		return this.severity;
	}

	public void setSeverity(Integer severity) {
		this.severity = severity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scriptTargetLog",cascade={CascadeType.ALL})
	public Set<ScriptTargetRowLog> getScriptTargetRowLogs() {
		return scriptTargetRowLogs;
	}

	public void setScriptTargetRowLogs(Set<ScriptTargetRowLog> scriptTargetRowLogs) {
		this.scriptTargetRowLogs = scriptTargetRowLogs;
	}

}
