package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Target generated by hbm2java
 */
@Entity
@Table(name = "psd_target", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class Target implements java.io.Serializable {

	private static final long serialVersionUID = -3580886102644833115L;
	
	private Integer targetId;
	private TargetType targetType;
	private int serverId;
	private String name;
	private String hostname;
	private String databaseName;
	private int portNumber;
	private String monitorUsername;
	private String salt;
	private String monitorPassword;
	private String statusCode;
	private Date inactiveUntil;
	private Date createSysdate;
	private Date updateSysdate;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "target_id", unique = true, nullable = false)
	public Integer getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Integer targetId) {
		this.targetId = targetId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "target_type_id", nullable = false)
	public TargetType getTargetType() {
		return targetType;
	}

	public void setTargetType(TargetType targetType) {
		this.targetType = targetType;
	}


	@Column(name = "server_id", nullable = false)
	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "hostname", nullable = false, length = 100)
	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "database_name", nullable = false, length = 100)
	public String getDatabaseName() {
		return this.databaseName;
	}

	public void setDatabaseName(String databaseName) {
		this.databaseName = databaseName;
	}

	@Column(name = "port_number", nullable = false)
	public int getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(int portNumber) {
		this.portNumber = portNumber;
	}

	@Column(name = "monitor_username", nullable = false, length = 30)
	public String getMonitorUsername() {
		return this.monitorUsername;
	}

	public void setMonitorUsername(String monitorUsername) {
		this.monitorUsername = monitorUsername;
	}

	@Column(name = "salt", nullable = false, length = 16)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "monitor_password", nullable = false, length = 30)
	public String getMonitorPassword() {
		return this.monitorPassword;
	}

	public void setMonitorPassword(String monitorPassword) {
		this.monitorPassword = monitorPassword;
	}

	@Column(name = "status_code", nullable = false, length = 1)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inactive_until", length = 19)
	public Date getInactiveUntil() {
		return this.inactiveUntil;
	}

	public void setInactiveUntil(Date inactiveUntil) {
		this.inactiveUntil = inactiveUntil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}
	
	/**
	 * Return connection URL
	 * @return
	 */
	@Transient
	public String getUrl() {
		String url = targetType.getUrlJdbc();
		url = url.replaceAll("%h",hostname);
		url = url.replaceAll("%p",""+portNumber);
		url = url.replaceAll("%d",databaseName);
		return url;
	}

}
