package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TargetType generated by hbm2java
 */
@Entity
@Table(name = "psd_target_type", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class TargetType implements java.io.Serializable {

	private static final long serialVersionUID = -4724862241992627136L;
	
	private Integer targetTypeId;
	private String name;
	private String urlRuby;
	private String urlJdbc;
	private Date createSysdate;
	private Date updateSysdate;

	public TargetType() {
	}

	public TargetType(String name, String urlRuby, String urlJdbc, Date createSysdate, Date updateSysdate) {
		this.name = name;
		this.urlRuby = urlRuby;
		this.urlJdbc = urlJdbc;
		this.createSysdate = createSysdate;
		this.updateSysdate = updateSysdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "target_type_id", unique = true, nullable = false)
	public Integer getTargetTypeId() {
		return this.targetTypeId;
	}

	public void setTargetTypeId(Integer targetTypeId) {
		this.targetTypeId = targetTypeId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url_ruby", nullable = false, length = 1000)
	public String getUrlRuby() {
		return this.urlRuby;
	}

	public void setUrlRuby(String urlRuby) {
		this.urlRuby = urlRuby;
	}

	@Column(name = "url_jdbc", nullable = false, length = 1000)
	public String getUrlJdbc() {
		return this.urlJdbc;
	}

	public void setUrlJdbc(String urlJdbc) {
		this.urlJdbc = urlJdbc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

}
