package com.untd.database.poseidon.model.database;
// Generated Dec 2, 2015 11:41:41 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TargetGroupAssignment generated by hbm2java
 */
@Entity
@Table(name = "psd_target_group_assignment", uniqueConstraints = @UniqueConstraint(columnNames = {
		"target_group_id", "target_id" }) )
public class TargetGroupAssignment implements java.io.Serializable {

	private static final long serialVersionUID = 6484880097105287490L;
	
	private Integer targetGroupAssignmentId;
	private int targetId;
	private int targetGroupId;
	private String statusCode;
	private Date inactiveUntil;
	private Date createSysdate;
	private Date updateSysdate;

	public TargetGroupAssignment() {
	}

	public TargetGroupAssignment(int targetId, int targetGroupId, String statusCode, Date createSysdate,
			Date updateSysdate) {
		this.targetId = targetId;
		this.targetGroupId = targetGroupId;
		this.statusCode = statusCode;
		this.createSysdate = createSysdate;
		this.updateSysdate = updateSysdate;
	}

	public TargetGroupAssignment(int targetId, int targetGroupId, String statusCode, Date inactiveUntil,
			Date createSysdate, Date updateSysdate) {
		this.targetId = targetId;
		this.targetGroupId = targetGroupId;
		this.statusCode = statusCode;
		this.inactiveUntil = inactiveUntil;
		this.createSysdate = createSysdate;
		this.updateSysdate = updateSysdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "target_group_assignment_id", unique = true, nullable = false)
	public Integer getTargetGroupAssignmentId() {
		return this.targetGroupAssignmentId;
	}

	public void setTargetGroupAssignmentId(Integer targetGroupAssignmentId) {
		this.targetGroupAssignmentId = targetGroupAssignmentId;
	}

	@Column(name = "target_id", nullable = false)
	public int getTargetId() {
		return this.targetId;
	}

	public void setTargetId(int targetId) {
		this.targetId = targetId;
	}

	@Column(name = "target_group_id", nullable = false)
	public int getTargetGroupId() {
		return this.targetGroupId;
	}

	public void setTargetGroupId(int targetGroupId) {
		this.targetGroupId = targetGroupId;
	}

	@Column(name = "status_code", nullable = false, length = 1)
	public String getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inactive_until", length = 19)
	public Date getInactiveUntil() {
		return this.inactiveUntil;
	}

	public void setInactiveUntil(Date inactiveUntil) {
		this.inactiveUntil = inactiveUntil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_sysdate", nullable = false, length = 19)
	public Date getCreateSysdate() {
		return this.createSysdate;
	}

	public void setCreateSysdate(Date createSysdate) {
		this.createSysdate = createSysdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_sysdate", nullable = false, length = 19)
	public Date getUpdateSysdate() {
		return this.updateSysdate;
	}

	public void setUpdateSysdate(Date updateSysdate) {
		this.updateSysdate = updateSysdate;
	}

}
