package com.untd.database.poseidon.data;

import java.util.Date;

public class ScriptTargetLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.script_target_log_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Integer scriptTargetLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.script_log_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Integer scriptLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.target_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Integer targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.start_date
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.finish_date
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Date finishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.status_number
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Integer statusNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.severity
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Integer severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.create_sysdate
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Date createSysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.update_sysdate
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private Date updateSysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_target_log.error_message
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    private String errorMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.script_target_log_id
     *
     * @return the value of psd_script_target_log.script_target_log_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Integer getScriptTargetLogId() {
        return scriptTargetLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.script_target_log_id
     *
     * @param scriptTargetLogId the value for psd_script_target_log.script_target_log_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setScriptTargetLogId(Integer scriptTargetLogId) {
        this.scriptTargetLogId = scriptTargetLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.script_log_id
     *
     * @return the value of psd_script_target_log.script_log_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Integer getScriptLogId() {
        return scriptLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.script_log_id
     *
     * @param scriptLogId the value for psd_script_target_log.script_log_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setScriptLogId(Integer scriptLogId) {
        this.scriptLogId = scriptLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.target_id
     *
     * @return the value of psd_script_target_log.target_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.target_id
     *
     * @param targetId the value for psd_script_target_log.target_id
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.start_date
     *
     * @return the value of psd_script_target_log.start_date
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.start_date
     *
     * @param startDate the value for psd_script_target_log.start_date
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.finish_date
     *
     * @return the value of psd_script_target_log.finish_date
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.finish_date
     *
     * @param finishDate the value for psd_script_target_log.finish_date
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.status_number
     *
     * @return the value of psd_script_target_log.status_number
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Integer getStatusNumber() {
        return statusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.status_number
     *
     * @param statusNumber the value for psd_script_target_log.status_number
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setStatusNumber(Integer statusNumber) {
        this.statusNumber = statusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.severity
     *
     * @return the value of psd_script_target_log.severity
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Integer getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.severity
     *
     * @param severity the value for psd_script_target_log.severity
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setSeverity(Integer severity) {
        this.severity = severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.create_sysdate
     *
     * @return the value of psd_script_target_log.create_sysdate
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Date getCreateSysdate() {
        return createSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.create_sysdate
     *
     * @param createSysdate the value for psd_script_target_log.create_sysdate
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setCreateSysdate(Date createSysdate) {
        this.createSysdate = createSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.update_sysdate
     *
     * @return the value of psd_script_target_log.update_sysdate
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public Date getUpdateSysdate() {
        return updateSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.update_sysdate
     *
     * @param updateSysdate the value for psd_script_target_log.update_sysdate
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setUpdateSysdate(Date updateSysdate) {
        this.updateSysdate = updateSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_target_log.error_message
     *
     * @return the value of psd_script_target_log.error_message
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_target_log.error_message
     *
     * @param errorMessage the value for psd_script_target_log.error_message
     *
     * @mbggenerated Thu Feb 06 10:59:54 GMT-08:00 2014
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}