package com.untd.database.poseidon.data;

import java.util.Date;

public class ScriptLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.script_log_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Integer scriptLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.script_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Integer scriptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.server_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Integer serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.start_date
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.finish_date
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Date finishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.status_number
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Integer statusNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.error_status_code
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Integer errorStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.trigger_status_code
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Integer triggerStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.create_sysdate
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Date createSysdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column psd_script_log.update_sysdate
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    private Date updateSysdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.script_log_id
     *
     * @return the value of psd_script_log.script_log_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Integer getScriptLogId() {
        return scriptLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.script_log_id
     *
     * @param scriptLogId the value for psd_script_log.script_log_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setScriptLogId(Integer scriptLogId) {
        this.scriptLogId = scriptLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.script_id
     *
     * @return the value of psd_script_log.script_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Integer getScriptId() {
        return scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.script_id
     *
     * @param scriptId the value for psd_script_log.script_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setScriptId(Integer scriptId) {
        this.scriptId = scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.server_id
     *
     * @return the value of psd_script_log.server_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.server_id
     *
     * @param serverId the value for psd_script_log.server_id
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.start_date
     *
     * @return the value of psd_script_log.start_date
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.start_date
     *
     * @param startDate the value for psd_script_log.start_date
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.finish_date
     *
     * @return the value of psd_script_log.finish_date
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.finish_date
     *
     * @param finishDate the value for psd_script_log.finish_date
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.status_number
     *
     * @return the value of psd_script_log.status_number
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Integer getStatusNumber() {
        return statusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.status_number
     *
     * @param statusNumber the value for psd_script_log.status_number
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setStatusNumber(Integer statusNumber) {
        this.statusNumber = statusNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.error_status_code
     *
     * @return the value of psd_script_log.error_status_code
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Integer getErrorStatusCode() {
        return errorStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.error_status_code
     *
     * @param errorStatusCode the value for psd_script_log.error_status_code
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setErrorStatusCode(Integer errorStatusCode) {
        this.errorStatusCode = errorStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.trigger_status_code
     *
     * @return the value of psd_script_log.trigger_status_code
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Integer getTriggerStatusCode() {
        return triggerStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.trigger_status_code
     *
     * @param triggerStatusCode the value for psd_script_log.trigger_status_code
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setTriggerStatusCode(Integer triggerStatusCode) {
        this.triggerStatusCode = triggerStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.create_sysdate
     *
     * @return the value of psd_script_log.create_sysdate
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Date getCreateSysdate() {
        return createSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.create_sysdate
     *
     * @param createSysdate the value for psd_script_log.create_sysdate
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setCreateSysdate(Date createSysdate) {
        this.createSysdate = createSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column psd_script_log.update_sysdate
     *
     * @return the value of psd_script_log.update_sysdate
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public Date getUpdateSysdate() {
        return updateSysdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column psd_script_log.update_sysdate
     *
     * @param updateSysdate the value for psd_script_log.update_sysdate
     *
     * @mbggenerated Thu Feb 06 10:36:09 GMT-08:00 2014
     */
    public void setUpdateSysdate(Date updateSysdate) {
        this.updateSysdate = updateSysdate;
    }
}